---
- name: RHC CloudForms Quickstart Install
  hosts: localhost
  connection: local
  gather_facts: false
  user: root

  vars:
    dest_dir: /root/
    github_user: jeffwarnica
    github_project: rhc-miq-quickstart
    cfme_base_dir: "{{ dest_dir }}{{ github_project }}"
    rht_base_dir: "{{ dest_dir }}cfme-rhconsulting-scripts"
    offline: false
    offline_rht_zip_file: "{{ dest_dir }}cfme-rhconsulting-scripts-master.zip"
    offline_cfme_zip_file: "{{ dest_dir }}CloudForms_Quickstart-master.zip"

  tasks:
  - name: Clone cfme-rhconsulting-scripts
    git:
      repo: https://github.com/rhtconsulting/cfme-rhconsulting-scripts.git
      dest: "{{ rht_base_dir }}"
    when: not offline

  - name: Unzipping "{{ offline_rht_zip_file }}"
    unarchive:
      src: "{{ offline_rht_zip_file }}"
      dest: "{{ dest_dir }}"
    when: offline

  - name: Move cfme-rhconsulting-scripts-master to "{{ rht_base_dir }}"
    command: mv "{{ dest_dir }}cfme-rhconsulting-scripts-master" "{{ rht_base_dir }}"
    when: offline

  - name:  Install the cfme-rhconsulting-scripts
    shell: make clean install
    args:
      chdir: "{{ rht_base_dir }}"

  - name: Clone CloudForms_Essentials
    git:
      repo: "https://github.com/{{ github_user }}/{{ github_project }}.git"
      dest: "{{ cfme_base_dir }}"
    when: not offline

  - name: Unzipping "{{ offline_cfme_zip_file }}"
    unarchive:
      src: "{{ offline_cfme_zip_file }}"
      dest: "{{ dest_dir }}"
    when: offline

  - name: Move Zip to "{{ cfme_base_dir }}"
    command: mv "{{ dest_dir }}CloudForms_Quickstart-master" "{{ cfme_base_dir }}"
    when: offline

  - name: Import automate domain
    shell: miqimport domain rhc-miq-quickstart "{{ cfme_base_dir }}/automate"
    args:
      chdir: "{{ cfme_base_dir }}"

  - name: Import dialogs
    shell: "miqimport service_dialogs service_dialogs/"
    args:
      chdir: "{{ cfme_base_dir }}"

  - name: Import catalogs
    shell: "miqimport service_catalogs service_catalogs/"
    args:
      chdir: "{{ cfme_base_dir }}"

  - name: Import tags
    shell: "miqimport tags tags/"
    args:
      chdir: "{{ cfme_base_dir }}"

#  - name: Import buttons
#    shell: "miqimport buttons buttons/"
#    args:
#      chdir: "{{ cfme_base_dir }}"
#
#  - name: Import alerts
#    shell: "miqimport alerts alerts/"
#    args:
#      chdir: "{{ cfme_base_dir }}"
#
#  - name: Import policies
#    shell: "miqimport policies policies/"
#    args:
#      chdir: "{{ cfme_base_dir }}"
#
#  - name: Import reports
#    shell: "miqimport reports reports/"
#    args:
#      chdir: "{{ cfme_base_dir }}"
#
#  - name: Import widgets
#    shell: "miqimport widgets widgets/"
#    args:
#      chdir: "{{ cfme_base_dir }}"