---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: PostProvision with Telemetry
    name: PostProvision
    inherits:
    description:
  fields:
  - common_meth1:
      value: process_telemetry_data
  - execute:
      value: add_vm_to_service
  - vmware_meth1:
      value: vmware_PostProvision
  - redhat_meth1:
      value: redhat_PostProvision
